spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/seplag
    username: seplag
    password: seplag123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: 3cPqR7vX2mK9nL5tY8wJ4bF6hD1sA0eG3cPqR7vX2mK9nL5tY8wJ4bF6hD1sA0eG
  expiration: 300000
  refresh-expiration: 3600000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: albuns

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true